### ISSUE TITLE
Mitu samasugust veeretust korraga

### ISSUE THREAD

**Issue by mihrits** [hannilo/rollbot-py#2]
Võimalus teha `!roll 3(2d6+2)`, mis oleks sama, mis `!roll 2d6+2` kaks korda järjest kirjutatuna. Erinevus `!roll 6d6+2` on see, et viimasel juhul on modiferi ainult ühe korra ja peaks arvutama välja õige modiferi.

See oleks kasulik näiteks olukordades, kui on multiattack ja läheb mitu korda järjest pihta, siis oleks muidu vaja iga attacki jaoks eraldi arvutada, aga nii saab kiiremini ja mugavamalt.

**Comment by hannilo** [comment]
Maybe pigem 3x2d6+2? Kiirem kirjutada.

**Comment by mihrits** [comment]
Nõus
